[package]
name = "blot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
gif = "0.12.0"
image = "0.24.7"
rand = "0.8.5"
tempfile = "3.8.0"
termsize = "0.1.6"
